### ISSUE TITLE
Adding color ramps for layer symbology

### ISSUE THREAD

**Issue by gteohub** [geojupyter/jupytergis#173]
Hi,

With regard to our meeting today, I opened an issue for JupyterGIS. 

GIS specialists like to work with easy-to-apply solutions that are visual, that is when a color ramp comes in handy. 
Based on the data (numerical, categorized etc.) you can choose a predefined style to visualize the data. This way you save a lot of time, because you don't need to specify each single class with a color. Based on the different kinds of data, you can apply different color ramps. If you have categories, you can apply strong differential colors. If you have spectral bands, you can visualize them as a gradually changing color (like in the screenshot). 

So first you need to choose the type of classification like graduated, categorized, rule-based etc. and then choose a predefined color ramp based on a predefined color (pastel-colors, grey-scale, etc.). In the case of the screenshot, it was a band with linear interpolation of the data, visualized with a gradual color ramp, with a blue color scheme. QGIS automatically chooses the classes (not by the GIS person), but you can change the thresholds by dobbelclicking them. 

In QGIS, you choose first the layer properties, and then go to the color ramp section and choose the preferred color scheme, then adjust the thresholds if necessary etc. to your needs. 

Hope I could explain well what I mean, feel free to ask if you have any questions!

Best,
Monika

<img width="938" alt="Screenshot 2024-10-04 at 14 23 22" src="https://github.com/user-attachments/assets/f9bd44d8-f76d-4d0b-b17e-6c9704b8fdf9">

**Comment by martinRenou** [comment]
This was implemented in #177, thanks for the suggestion!
