### ISSUE TITLE
Open .jgis files with the JSON viewer

### ISSUE THREAD

**Issue by SylvainCorlay** [geojupyter/jupytergis#176]
Just like .ipynb files, it would be great to be able to open .jgis files with the JSON editor:

![374361397-e3e4b9e3-91fb-43f4-8c0f-ad3f66839014](https://github.com/user-attachments/assets/bb8f73e5-85fa-4384-b42f-f8025794b331)

This is the same issue as JupyterCAD's https://github.com/jupytercad/JupyterCAD/issues/454 by @jtpio.

**Comment by gjmooney** [comment]
Added in #210
