### ISSUE TITLE
QGIS project & projection

### ISSUE THREAD

**Issue by annefou** [geojupyter/jupytergis#191]
I created a new project in QGIS, added an openStreetMap layer and changed the projection (for instance to World_Aitoff). Then I saved my QGIS project and opened it in JupyterGIS. The QGIS project opens (in my local installation of JupyterGIS) but the layer does not appear. Below is what I have in QGIS:

![image](https://github.com/user-attachments/assets/bfe95271-99c1-4e40-bac0-a54d267cbc69)

**Comment by martinRenou** [comment]
in #196 

> We may want to start looking into using https://github.com/proj4js/proj4js to support other projection types
> 
> There is an example here https://openlayers.org/en/latest/examples/wms-image-custom-proj.html using proj4js with OpenLayers

**Comment by martinRenou** [comment]
https://github.com/josueggh/proj4-list/blob/master/src/list.js
