### ISSUE TITLE
Fix flacky UI-tests

### ISSUE THREAD

**Issue by brichet** [geojupyter/jupytergis#207]
Some UI-tests are comparing snapshots to ensure the map are correctly displayed.

These tests often fail when the map is not loaded when the snapshot is captured.

Maybe OpenLayer dispatch event when the map is loaded.
We could use this event in test to wait for the map to be ready.

**Comment by mfisher87** [comment]
On our call yesterday we considered whether the [`rendercomplete`](https://openlayers.org/en/latest/apidoc/module-ol_render_Event-RenderEvent.html) event would work.

**Comment by martinRenou** [comment]
It seems it got better after https://github.com/geojupyter/jupytergis/pull/214, thanks @brichet !
