### ISSUE TITLE
Cannot open Jupyterlite deployment: Directory not found: "RTC:"

### ISSUE THREAD

**Issue by arjxn-py** [geojupyter/jupytergis#212]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/08a5a23b-e5b9-451f-99a2-635c024f33fc">

**Comment by martinRenou** [comment]
Thanks! This may be due to the latest update of jupyter collaboration, we should port the lite environment from jupytercad

**Comment by martinRenou** [comment]
The new lite deployment should soon be live for us to try
