### ISSUE TITLE
Make the "visible" and "hidden" layer icons more differentiable

### ISSUE THREAD

**Issue by mfisher87** [geojupyter/jupytergis#224]
I think we need to pick one of these icons to make more prominent and keep the other one subtle as-is, i.e. make the "visible" icon more prominent by bolding it and giving it a "yes/on" color like blue or green, OR make the "hidden" icon more prominent by making bold and a "no/off" color like red.

Thoughts?

**Comment by mfisher87** [comment]
I think this would be a good low-stakes task I can take on! It will fit well with my busy interview schedule and give me a chance to "onboard" a bi more.

**Comment by martinRenou** [comment]
Sounds good! I agree this button requires a bit of love.

Adding a note that, for some reason, we're not using the same icon in JupyterGIS and JupyterCAD. We should share the same component for both.

We should really think of making a toolkit to share some logic between JupyterGIS and JupyterCAD, this may be tricky without complicating further the development cycles, but for small components like this one it would make sense.

That being said, I'd be happy to see the component in JupyterGIS being improved for now, then we can think of extracting it somewhere so JupyterCAD can use it.

**Comment by arjxn-py** [comment]
I'm happy to look into it.
Also the plan makes sense, open to discuss and iterate.

**Comment by mfisher87** [comment]
See also #231
