### ISSUE TITLE
Add conda install instructions to README

### ISSUE THREAD

**Issue by matthewfeickert** [geojupyter/jupytergis#227]
This is a really great project to see! I see from some searching that `jupytergis` is already on conda-forge at the https://github.com/conda-forge/jupytergis-packages-feedstock feedstock. It would be great to have this advertised on the install instructions as well.

**Comment by mfisher87** [comment]
Great catch, thank you!

**Comment by matthewfeickert** [comment]
Also c.f. https://github.com/conda-forge/jupytergis-packages-feedstock/pull/2#issuecomment-2526705769 to get the `v0.1.7` release up on conda-forge.
