### ISSUE TITLE
Cannot open GeoJSON files anymore

### ISSUE THREAD

**Issue by martinRenou** [geojupyter/jupytergis#235]
![Screenshot From 2024-12-10 15-43-19](https://github.com/user-attachments/assets/ec442273-a633-48dd-b2bb-5ba6a172df56)

**Comment by mfisher87** [comment]
See #238 for more examples that don't open!

**Comment by arjxn-py** [comment]
You were right @martinRenou, this is most likely due to #165, and I was also wrong about that this issue persists in JupyterLAB as it doesn't.
