### ISSUE TITLE
Unable to add GeoJSON layer

### ISSUE THREAD

**Issue by mfisher87** [geojupyter/jupytergis#238]
I've been unable to find a GeoJSON layer that will pass the validation when entering a filename in the add GeoJSON Layer menu.

![image](https://github.com/user-attachments/assets/6e3a6f31-15c0-488c-b927-5d8c9aeda478)

* `eq.json` 
* GeoJSON from: https://cartographyvectors.com/map/372-joshua-tree-national-park
* GeoJSON from GADM

The error messages are a bit unfriendly as well :)

**Comment by martinRenou** [comment]
I believe it may be related to  #235

**Comment by mfisher87** [comment]
Yeah, good call! I'll close this one and update the title of the other.

**Comment by mfisher87** [comment]
I was also unable to load the shapefile from the cartographyvectors.com source above. I need to reproduce it again and open an issue, but it looked something like: the data in the shapefile didn't display, and changes made in the layer panel had no effect (e.,g. show/hide layers) until removing the shapefile layer. I was able to load a vector PMTiles layer with no problems!

**Comment by martinRenou** [comment]
Shapefiles are turned into GeoJSON before displaying on the OpenLayers, so it is a related problem too.
