### ISSUE TITLE
Setup pre-commit-ci

### ISSUE THREAD

**Issue by martinRenou** [geojupyter/jupytergis#247]
https://github.com/apps/pre-commit-ci

**Comment by mfisher87** [comment]
:100:

**Comment by mfisher87** [comment]
Installed for all geojupyter repositories!

**Comment by mfisher87** [comment]
Checks working on this repo: https://results.pre-commit.ci/repo/github/813604742

Autofix automation working on this PR: https://github.com/geojupyter/jupytergis/pull/243

Although I think I prefer autofixes to be off, but that's just me! :)
