### ISSUE TITLE
Automatically open a Python repl with access to the document

### ISSUE THREAD

**Issue by martinRenou** [geojupyter/jupytergis#41]
Similar to what tools like Mayavi/Freecad/Blender do, we should automatically provide a Python repl with access to the document:

![Screenshot from 2024-07-11 15-00-37](https://github.com/QuantStack/jupytergis/assets/21197331/6fb6ed16-1a8a-434e-a6ab-19976818158a)

Ideally (probably some items are long term) we would:
- [ ] Pre-execute the opening of the `GISDocument` and expose it as `gis` or `doc` in the Python scope.
- [ ] Save the state and history of the repl in the jGIS document
- [ ] Make the repl collaborative too

**Comment by davidbrochart** [comment]
So this REPL would be a shortcut to creating a new notebook and writing in the first cell the following code?
```python
from jupyterlab_gis import GISDocument

doc = GISDocument("my_document.jGIS")
```
The state/history is saved in the notebook file already, and the notebook can be collaborative.
Maybe a button like "Create new notebook/console from document" would be enough?

**Comment by davidbrochart** [comment]
> Wild idea, could the `jGIS` format/ydoc be just an extension of the Notebook?

Or stored somewhere in the notebook metadata?

**Comment by martinRenou** [comment]
I was also thinking of this idea 😄 Then that would still be a notebook

**Comment by martinRenou** [comment]
We should port https://github.com/jupytercad/JupyterCAD/pull/392 to JupyterGIS 🚀
