### ISSUE TITLE
CORS Error When Loading OPNVKarte Basemap

### ISSUE THREAD

**Issue by arjxn-py** [geojupyter/jupytergis#93]
When attempting to load the OPNVKarte basemap in JupyterGIS, a CORS (Cross-Origin Resource Sharing) error is encountered, preventing the tiles from being fetched and displayed.

```
Access to fetch at 'https://tileserver.memomaps.de/tilegen/4/11/7.png' from origin 'http://localhost:8888' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://tileserver.memomaps.de/tilegen/4/11/7.png net::ERR_FAILED 200 (OK)

```

**Comment by arjxn-py** [comment]
Apologies in advance as I know that the project is WIP but one more reason to open this issue is that I'm facing the same problem in [arjxn-py/jupytergis#1](https://github.com/arjxn-py/jupytergis/pull/1), see [this commit](https://github.com/arjxn-py/jupytergis/pull/1/commits/fd877a91af4fc5342cbd3b9ecd9358d87f2600e6) in which i just did a hacky workaround but definitely not for production.

**Comment by arjxn-py** [comment]
`ProxyHandler` defined in #104 should come in handy to fix this as well. But since it'd still not work with JupyterLite, would we want to also add a note or warning if we decide to use that upon agreement?

**Comment by martinRenou** [comment]
I guess that in the case of jupyterlite we can rely on cors-anywhere for now? We could think of making our own deployment of a cors-anywhere-like server

**Comment by arjxn-py** [comment]
> I guess that in the case of jupyterlite we can rely on cors-anywhere for now? We could think of making our own deployment of a cors-anywhere-like server

Oh yes, this sounds promising. I didn't actually thought about serving that ourselves but it's definitely can be explored and I would be up for it.

**Comment by arjxn-py** [comment]
Closing as completed since this issue is no longer there
